{{- if .Values.externalSecrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "docker-registry.fullname" . }}
spec:
{{- with .Values.externalSecrets }}
  {{- . | toYaml | nindent 2 }}
{{- end }}
{{- end }}
