{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
{{- $servicemonitornamespace := .Values.metrics.serviceMonitor.namespace | default .Release.Namespace }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "docker-registry.serviceMonitorName" . }}
  namespace: {{ $servicemonitornamespace }}
  labels:
    {{- include "docker-registry.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - path: /metrics
      port: metrics-port
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.timeout }}
  selector:
    matchLabels:
      {{- include "docker-registry.selectorLabels" . | nindent 6 }}
{{-  end }}
