---
name: build comet action runner
run-name: Build comet action runner ${{ github.ref_name }} by @${{ github.actor }}
on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
  
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Install Helm
      uses: azure/setup-helm@v4.2.0
      id: install

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.6.0
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

